version: "2"
services: 

  web:
    restart: always
    build: .
    ports: 3000:3000
    links:
      - mon
    
  mon:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/mon

    